name: Executar Script Node.js

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # PASSO ADICIONADO: Instala o dotenv (e outras dependências necessárias)
      - name: Instalar dependências
        run: npm install dotenv

      - name: Executar script JS
        run: node api_comlub.js
